# Generated by Django 5.1.7 on 2025-03-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='pnumber',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='repassword',
        ),
    ]
