# Generated by Django 5.1.7 on 2025-03-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_password_registration_pnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='pnumber',
            field=models.IntegerField(),
        ),
    ]
